language: ruby
before_install:
# disable rvm, use system Ruby
- rvm reset
- wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
- sh ./travis_setup.sh -p "yast2-devtools yast2 rake" -g "rspec:3.3.0 yast-rake gettext coveralls rubocop:0.41.2 cheetah"
script:
- rake check:pot
- rubocop
- COVERAGE=1 rake test:unit
- sudo rake install
